#!/bin/bash

# Fully Combined MMPBSA-like Energy Extraction Script
# Includes:
# - SASA & Nonpolar energy (NACCESS)
# - Polar solvation + Coulombic energy (Delphi via pdb2pqr)
# - VDW energy (NAMD minimization)
#
# Usage: ./mmpbsa_full.sh trajectory.pdb REC_CHAIN LIG_CHAIN PREFIX
# Example: ./mmpbsa_full.sh complex_traj.pdb A B equil

if [ $# -ne 4 ]; then
    echo "Usage: $0 input_trajectory.pdb chain_receptor chain_ligand prefix"
    echo "  e.g. $0 complex_traj.pdb A B equil"
    exit 1
fi

INPUT_PDB=$1
REC_CHAIN=$2
LIG_CHAIN=$3
PREFIX=$4

# ────────────────────── Paths (adjust if needed) ──────────────────────
NACCESS=~/Documents/Naccess/naccess          # NACCESS executable
PDB2PQR=~/Documents/pdb2pqr/pdb2pqr.py        # pdb2pqr script
DELPHI=Delphi85                              # Delphi executable (or full path)
NAMD=namd2                                  # NAMD executable (or full path)

# Nonpolar parameters (common literature values)
GAMMA=0.0054   # kcal/mol/Å²   
BETA=0.92      # kcal/mol

# Template config for NAMD (must exist in current directory)
TEMPLATE_CONFIG=complex.config

# ────────────────────── Output directories & files ──────────────────────
mkdir -p energies
cd energies 

# Empty output files
for f in SASA ele solv nonpol Vdw; do
    > ${f}_rec.txt
    > ${f}_lig.txt
    > ${f}_complex.txt
done

# ────────────────────── Prepare trajectory ──────────────────────
if [ "$(head -1 "../$INPUT_PDB" | awk '{print $1}')" != "ATOM" ]; then
    sed '1d' "../$INPUT_PDB" > cleaned.pdb
else
    cp "../$INPUT_PDB" cleaned.pdb
fi

grep -n END cleaned.pdb > end_pos.txt
sed -i 's/:/ /g' end_pos.txt
num_frames=$(wc -l end_pos.txt | awk '{print $1}')

echo "Found $num_frames frames. Starting processing..."

# ────────────────────── Main frame loop ──────────────────────
for ((frame=1; frame<=$num_frames; frame++)); do

    echo "=== Processing frame $frame / $num_frames ==="

    echo "=== Processing frame configure files preperation  ==="

    mkdir -p "$frame"
    cd "$frame" 
    cp ../../Config/* ./ 
    
    # Extract frame
    sep_line=$(head -$frame ../end_pos.txt | tail -1 | awk '{print $1}')
    num_atoms=$(head -1 ../end_pos.txt | awk '{print $1}')  # approximate

    head -$sep_line ../cleaned.pdb | tail -$num_atoms > complex.pdb

    # Separate chains CHARMM-GUI using PROA/B which is 76 while Chain ID is 22
    awk -v C="$REC_CHAIN" 'substr($0,76,1)==C {print}' complex.pdb > rec.pdb
    awk -v C="$LIG_CHAIN" 'substr($0,76,1)==C {print}' complex.pdb > lig.pdb

    # ──────── 1. SASA & Nonpolar (NACCESS) ────────
    $NACCESS rec.pdb > /dev/null 2>&1
    $NACCESS lig.pdb > /dev/null 2>&1
    $NACCESS complex.pdb > /dev/null 2>&1

    # Total SASA (column 2 after TOTAL)
    sasa_rec=$(awk '/^TOTAL/ {print $2; exit}' rec.rsa)
    sasa_lig=$(awk '/^TOTAL/ {print $2; exit}' lig.rsa)
    sasa_com=$(awk '/^TOTAL/ {print $2; exit}' complex.rsa)

    nonpol_rec=$(echo "$GAMMA * $sasa_rec + $BETA" | bc -l)
    nonpol_lig=$(echo "$GAMMA * $sasa_lig + $BETA" | bc -l)
    nonpol_com=$(echo "$GAMMA * $sasa_com + $BETA" | bc -l)

    echo "$sasa_rec"   >> ../SASA_rec.txt
    echo "$sasa_lig"   >> ../SASA_lig.txt
    echo "$sasa_com"   >> ../SASA_complex.txt
    echo "$nonpol_rec" >> ../nonpol_rec.txt
    echo "$nonpol_lig" >> ../nonpol_lig.txt
    echo "$nonpol_com" >> ../nonpol_complex.txt

    # ──────── 2. Polar + Coulombic (Delphi) ────────
    $PDB2PQR --ff=charmm --chain complex.pdb complex.pqr 
    $PDB2PQR --ff=charmm --chain rec.pdb rec.pqr 
    $PDB2PQR --ff=charmm --chain lig.pdb lig.pqr 

   # If The complex is generated by CHARMM-GUI, using substr($0,76,1); otherwise use substr($0,22,1).
   #  awk -v C="$REC_CHAIN" 'substr($0,76,1)==C {print}' complex.pqr > rec.pqr
   #  awk -v C="$LEG_CHAIN" 'substr($0,76,1)==C {print}' complex.pqr > lig.pqr

    # Delphi param files (here-document)
    for sys in rec lig complex; do
        file="${sys}.pqr"
        param="param_${sys}.txt"
        cat > "$param" << EOF
scale=2
perfil=70.0
in(modpdb4,file="$file",format = pqr)
indi=2.0
exdi=80.0
prbrad=1.4
salt=0.2
bndcon=2
maxc=0.001
linit=8000
energy(s,c,g)
EOF
    $DELPHI $param > out_${sys}.txt
    done

    grep Coulombic out_rec.txt | tail -1 >> ../ele_rec.txt
    grep Coulombic out_lig.txt | tail -1 >> ../ele_lig.txt
    grep Coulombic out_complex.txt | tail -1 >> ../ele_complex.txt

    grep "Corrected reaction field energy" out_rec.txt | tail -1 >> ../solv_rec.txt
    grep "Corrected reaction field energy" out_lig.txt | tail -1 >> ../solv_lig.txt
    grep "Corrected reaction field energy" out_complex.txt | tail -1 >> ../solv_complex.txt

    # ──────── 3. VDW (NAMD minimization) ────────
    mkdir -p out_complex out_rec out_lig

    # Generate NAMD config files
  
    # ──────── 3. VDW (NAMD minimization with AutoPSF per system) ────────
    mkdir -p out_complex out_rec out_lig

    for sys in complex rec lig; do
        echo "  → Processing $sys system (frame $frame)"

        input_pdb="${sys}.pdb"
        psf_file="${sys}.psf"
        fixed_pdb="${sys}_fixed.pdb"
        tcl_script="autopsf_${sys}.tcl"
        config_file="${sys}_config.conf"
        out_dir="out_${sys}"

        # ───────────────────────────────
        # 1. Generate AutoPSF TCL script
        # ───────────────────────────────
        cat > "$tcl_script" << EOF
package require psfgen
package require autopsf

resetpsf

topology top_all36_prot.rtf
# topology top_all36_na.rtf
# topology top_all36_carb.rtf
# topology top_all36_lipid.rtf   # uncomment if needed
# topology top_all36_cgenff.rtf  # for small molecules if needed

# AutoPSF – automatic patching, termini, disulfides, etc.
autopsf -mol [mol new $input_pdb type pdb waitfor all] \
        -prefix ${sys}_autopsf \
        -top top_all36_prot.rtf \
        -protein \
        -debug

puts "AutoPSF finished for $sys"
quit
EOF

        # Run VMD in batch mode
        vmd -dispdev text -e "$tcl_script" > autopsf_${sys}.log 

        # Check success
        if [ ! -f "${sys}_autopsf.psf" ] || [ ! -f "${sys}_autopsf.pdb" ]; then
            echo "ERROR: AutoPSF failed for $sys in frame $frame → see autopsf_${sys}.log"
            continue 2   # skip this whole frame
        fi

        # Rename outputs for clarity
        mv "${sys}_autopsf.psf" "$psf_file"
        mv "${sys}_autopsf.pdb" "$fixed_pdb"

        # ───────────────────────────────
        # 2. Generate NAMD config file
        # ───────────────────────────────
        cat > "$config_file" << EOF
# AUTO-GENERATED NAMD config – $sys – frame $frame

structure          $psf_file
coordinates        $fixed_pdb

set temperature    310.15
set outputname     ./$out_dir/${PREFIX}_${frame}

firsttimestep     0

paraTypeCharmm          on
parameters                par_all36m_prot.prm
# parameters              ../toppar/par_all36_na.prm
# parameters              ../toppar/par_all36_carb.prm
# parameters              ../toppar/par_all36_lipid.prm
# parameters              ../toppar/par_all36_cgenff.prm
# Add ligand-specific parameters here if needed, e.g.:
# parameters              ../toppar/ligand_${frame}.prm

temperature         \$temperature

gbis                on
alphaCutoff         12.0
ionConcentration    0.20

exclude             scaled1-4
1-4scaling          1.0
cutoff              14.0
switching           on
switchdist          13.0
pairlistdist        18.0

timestep            1.0
rigidBonds          all
nonbondedFreq       1
fullElectFrequency  1
stepspercycle       1

langevin            on
langevinDamping     1
langevinTemp        \$temperature
langevinHydrogen    off

outputName          \$outputname
restartfreq         500
dcdfreq             25
xstFreq             25
outputEnergies      10
outputPressure      10

minimize            1           ;# adjust number of steps as needed
#equilibration steps can be added here if desired
reinitvels          \$temperature
EOF

        # ───────────────────────────────
        # 3. Run NAMD minimization
        # ───────────────────────────────
        $NAMD "$config_file" > "$out_dir/log.txt" 

        # Extract VDW energy (last ENERGY line, column 8 = VDW)
        grep ENERGY "$out_dir/log.txt" | tail -1 | awk '{print $8}' >> ../Vdw_${sys}.txt

    done   # end of for sys in complex rec lig
  cd ../ # back to energies/
done
# ────────────────────── Cleanup (optional) ──────────────────────
rm cleaned.pdb end_pos.txt
# rm -rf [0-9]*   # uncomment if you don't want per-frame folders

echo "=================================================="
echo "$4's project done! Energy components collected in 'energies/' folder:"
ls -1 *.txt | sort
echo ""
echo "Files:"
echo "  SASA_*.txt          → total SASA (Å²)"
echo "  nonpol_*.txt        → nonpolar energy = γ×SASA + β (kJ/mol)"
echo "  ele_*.txt           → Coulombic energy (from Delphi)"
echo "  solv_*.txt          → Polar solvation energy (from Delphi)"
echo "  Vdw_*.txt           → Van der Waals energy (from NAMD, kcal/mol)"
echo ""
echo "Next steps:"
echo "  1. Convert Delphi units if needed (often kT → kcal/mol: × 0.592 at 298K)"
echo "  2. Compute averages and ΔG per frame in Excel/Python:"
echo "     ΔG ≈ [VDW_com + ele_com + solv_com + nonpol_com]"
echo "          - [VDW_rec + ele_rec + solv_rec + nonpol_rec]"
echo "          - [VDW_lig + ele_lig + solv_lig + nonpol_lig]"
echo "  3. Entropy (-TΔS) is still missing — consider Interaction Entropy or Normal Modes for better accuracy."
echo "=================================================="

# +++++++++++++++++++++ Back to Project Root++++++++++++++++++++++ 
cd ../
